global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-profile-service'
    static_configs:
      - targets: ['user-profile-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'project-ideas-service'
    static_configs:
      - targets: ['project-ideas-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'matching-service'
    static_configs:
      - targets: ['matching-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'content-ingestion-service'
    static_configs:
      - targets: ['content-ingestion-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 5s
