apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: analytics-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        tier: backend
    spec:
      containers:
      - name: analytics-service
        image: skill-sync/analytics-service:latest
        ports:
        - containerPort: 3007
        env:
        - name: PORT
          value: "3007"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/skillsync_analytics"
        - name: RABBITMQ_URL
          value: "amqp://admin:password123@rabbitmq:5672"
        - name: REDIS_URL
          value: "redis://redis:6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "800m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3007
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3007
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
  - port: 3007
    targetPort: 3007
    protocol: TCP
  type: ClusterIP
