apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  labels:
    app: websocket-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
        tier: backend
    spec:
      containers:
      - name: websocket-service
        image: skill-sync/websocket-service:latest
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: "3006"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/skillsync_realtime"
        - name: RABBITMQ_URL
          value: "amqp://admin:password123@rabbitmq:5672"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: ALLOWED_ORIGINS
          value: "http://localhost:3000,http://localhost:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app: websocket-service
spec:
  selector:
    app: websocket-service
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  secret: "your-super-secret-jwt-key-change-this-in-production"
