name: Project Ideas Service CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'services/project-ideas-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/project-ideas-service/**'

env:
  SERVICE_NAME: project-ideas-service
  REGISTRY: ghcr.io
  IMAGE_NAME: skill-sync/project-ideas-service

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: services/project-ideas-service/package-lock.json

    - name: Install dependencies
      working-directory: services/project-ideas-service
      run: npm ci

    - name: Run linting
      working-directory: services/project-ideas-service
      run: npm run lint

    - name: Run tests
      working-directory: services/project-ideas-service
      run: npm test
      env:
        MONGODB_URI: mongodb://localhost:27017/skillsync_projects_test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: services/project-ideas-service
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        sed -i "s|skill-sync/project-ideas-service:latest|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/project-ideas-service-deployment.yaml
        kubectl apply -f k8s/project-ideas-service-deployment.yaml
        kubectl rollout status deployment/project-ideas-service --timeout=300s
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
